Add configurable sluice properties
FTBTeam/FTB-Sluice pull request #4
Opened 2021-12-01 04:05 UTC by MasterOfBob777

Fixes https://github.com/FTBTeam/FTB-Mods-Issues/issues/120

2021-12-01 15:54 UTC, MichaelHillcox requested changes
Please revert all formatting changes.

2021-12-01 16:01 UTC, MasterOfBob777 commented
Sorry that was unintentional, I'll fix that.

2021-12-01 16:51 UTC, MaxNeedsSnacks commented
For reference, we should probably look into adding .editorconfigs to our mods, seeing as each of the FTB authors has their own code style :p

2021-12-04 21:30 UTC, MichaelHillcox approved these changes

2021-12-04 21:30 UTC, merged